### PR TITLE
Feature/multiple elastic nodes

### PR DESCRIPTION
**Pull request by eran-gil**
I added the option to add multiple elastic nodes to the configuration. My only concern here is the ssl logic, which I think is not best, but still should be functioning well.

### CODE REVIEW

**Comment by urielha** [comment]
Thanks 😄 
Though I don't want to break old users' configuration so I want to keep the option to configure one server (I think it would be easy to keep it coexists with your changes).
All seems pretty well, I hope to look at all the requests this week and publish new release.

**Comment by urielha** [comment]
and it seems like my travis build is broken from some reason, I will fix it too

**Comment by eran-gil** [comment]
Added support for old configuration parameters

**Comment by eran-gil** [comment]
Done :)

**Comment by urielha** [comment]
Hi, Please at the next time do your changes on top of the last changes you have sent as pull request.
This caused me a bunch of unpleasant conflicts which could be avoided.

Indeed, thanks a lot for all the contributions!

**Pull request closed without merging**
