### PR TITLE
Added ApiKey authentication method

### PR DESCRIPTION
**Pull request by dannyyy**
Successfully tested with Elasticsearh 7.6.0

PR according to #60

### CODE REVIEW

**Comment by eran-gil** [comment]
I recommend adding two options to enter the API key.
1. with the base64 data as you have done already
2. with 2 parameters for API key and id, and the authenticator will do the conversion to base64.

These cannot be used together, and thus there should be a "master" way that decides when all properties are used. I recommend using the base 64 as master.

**Comment by dannyyy** [comment]
@erangil2 Thanks for your recommendation.
@urielha Any chance to get this change published (incl. NuGet) in the next two days? Currently it's hindering to migrate projects. In that case we have to going to switch the dependecies to my own fork, that would be a pitty.

**Comment by eran-gil** [comment]
Was the new addition tested with ElasticSearch? If so I'll contact @urielha and see what we can do

**Comment by dannyyy** [comment]
> Was the new addition tested with ElasticSearch? If so I'll contact @urielha and see what we can do

Yes, both methods were tested against Elasticsearch 7.6.0 with enabled X-Pack. Also the special case where `ApiKeyBase64` and `Id/ApiKey` was present has been tested successfully. The `ApiKeyBase64` configuration took precedence over the later one.

**Review by urielha — APPROVED** [review]
Thanks for the PR, sorry for my low availability.
I'll merge it and hope to publish it ASAP

**Pull request merged**
