### PR TITLE
json filter

### PR DESCRIPTION
**Pull request by ignasv**
JSON parsing filter added. It takes an existing field which contains JSON and expands it into an actual data structure within the log event.

### CODE REVIEW

**Comment by urielha** [comment]
Actually I've already added such a filter in Dev branch but I will take a look, maybe I can merge the two.
Thanks!!

**Comment by urielha** [comment]
Now I see that I didn't push it yet :sweat_smile:

**Comment by ignasv** [comment]
Heh, bad timing on my side :) anyway, see if you can find anything useful in my PR, and let me know if I can help in any way.

**Comment by urielha** [comment]
it's never bad timing. In addition, I think your approach is better :)

**Comment by urielha** [comment]
Merged into master with few changes - I want to preserve the structure of the json.

**Pull request merged**
